# Generated by Django 6.0.6 on 2026-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('material_type', models.CharField(choices=[('article', 'Статья'), ('lesson', 'Урок'), ('methodical', 'Методический материал')], max_length=32, verbose_name='Тип')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='education/', verbose_name='Обложка')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='education/files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Образовательный материал',
                'verbose_name_plural': 'Образовательные материалы',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
