# Generated by Django 6.0.6 on 2026-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewspaperIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('issue_number', models.PositiveIntegerField(verbose_name='Номер выпуска')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='newspapers/covers/', verbose_name='Обложка')),
                ('pdf_file', models.FileField(upload_to='newspapers/pdf/', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Выпуск газеты',
                'verbose_name_plural': 'Выпуски газеты',
                'ordering': ['-issue_number', '-published_at'],
                'abstract': False,
            },
        ),
    ]
